name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add SSH known hosts to avoid authenticity prompt
      - name: Setup SSH Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Production (main branch)
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/frankporter/Frankporter_Backend/
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsa
            
            # Ensure Git uses SSH for authentication
            git config --global user.email "Raveena.mexxiss@gmail.com"
            git config --global user.name "Raveena"
            git remote set-url origin git@github.com:mexxiss/Frankporter_Backend.git

            # Pull latest changes
            sudo git pull origin main

            # Install dependencies and build
            sudo npm install

            # Show Git status
            sudo git status
            pm2 restart Frankporter_Backend
